#!/usr/bin/env python

import telebot,sys

BOT_TOKEN='your_bot_token'

DESTINATION=sys.argv[1]

SUBJECT=sys.argv[2]

MESSAGE=sys.argv[3]

MESSAGE = MESSAGE.replace('/n','\n')

tb = telebot.TeleBot(BOT_TOKEN)

tb.send_message(DESTINATION,SUBJECT + '\n' + MESSAGE)


##########################################################

# don't forget set permission to file:
    # 1. chown -R zabbix telegram
    # 1. chmod +x telegram
